version: "3.5"

services:
  redis:
    build:
      context: ./image
      dockerfile: Dockerfile
    container_name: redis
    restart: unless-stopped
    volumes:
      - ./conf:/usr/local/etc/redis
      - ./data:/data
